/* eslint-disable */
export const FORM_SCHEMAS = {
  boisboreal: [
    {section:"📐 Métrés principaux"},
    {id:"mob_m2",label:"Surface MOB (murs ossature bois)",unit:"m²",hint:"Toutes faces extérieures"},
    {id:"ite_m2",label:"Surface ITE PSE 100mm",unit:"m²",hint:"Façade enduite (souvent ≈ MOB) — tableaux inclus"},
    {id:"laine_m2",label:"Surface laine de verre 120mm",unit:"m²",hint:"= MOB −10% auto"},
    {id:"pv_m2",label:"Surface pare-vapeur SD100",unit:"m²",hint:"Généralement = MOB"},
    {id:"protection_tete_ml",label:"Protection en tête de MOB",unit:"ML",hint:"= MOB −30% auto (4,60 €/ML)"},
    {section:"🏗️ Plancher (optionnel)"},
    {id:"plancher_clt",label:"Plancher CLT 140 5L",unit:"m²",hint:"Laisser 0 si pas de plancher bois"},
    {section:"🏠 Charpente"},
    {id:"fermette_qty",label:"Ensemble charpente fermette",unit:"forfait",hint:"1 = inclure, 0 = sans"},
    {section:"🚪 Ouvrages annexes"},
    {id:"vr_qty",label:"Coffres volet roulant",unit:"u",hint:"Nombre de baies à VR"},
    {id:"appuis_seuil_qty",label:"Appuis et seuils PSE",unit:"u",hint:"59,29 €/u"},
    {section:"🚚 Logistique"},
    {id:"chargement_m2",label:"Chargement atelier",unit:"m²",hint:"= MOB auto (5,17 €/m²)"},
    {id:"transport",label:"Transport",unit:"€",hint:"Auto : 1 ou 2 forfaits × 1 268 €"},
    {section:"📋 Frais fixes"},
    {id:"etude",label:"Bureau d'étude",unit:"forfait",hint:"Quasi-figé à 1 938 €",default:1938}
  ],
  cobs: [
    {section:"📐 Parois"},
    {id:"mob_m2",label:"Surface paroi ossature bois",unit:"m²",hint:"Surface totale MOB"},
    {id:"isolation_m2",label:"Isolation laine 120mm + pare-vapeur",unit:"m²",hint:"Surface isolée"},
    {id:"ite_m2",label:"ITE polystyrène 100mm",unit:"m²",hint:"Pour pose enduit"},
    {section:"🔲 Pièces d'appui & menuiseries"},
    {id:"appui_qty",label:"Pièces d'appui béton préfa",unit:"u",hint:"Coffrelite ou équivalent"},
    {id:"pose_menui_qty",label:"Pose de menuiserie en atelier",unit:"u",hint:"Nombre de menuiseries posées"},
    {id:"pose_coffre_qty",label:"Pose de coffre",unit:"u",hint:"10 €/u"},
    {section:"🏠 Toiture & couverture"},
    {id:"charpente_m2",label:"Charpente industrielle (fermettes)",unit:"m²",hint:"Surface de toiture"},
    {section:"🪵 Plancher (optionnel)"},
    {id:"plancher_m2",label:"Plancher solivage BLC",unit:"m²",hint:"Laisser 0 si pas de R+1"},
    {section:"🚚 Logistique"},
    {id:"livraison",label:"Livraison (forfait €)",unit:"€",hint:"Moy. 1 556 €"},
    {section:"📋 Frais fixes"},
    {id:"etude",label:"Étude complète",unit:"forfait",hint:"Moy. 833 €",default:833}
  ],
  sicob: [
    {section:"📐 Murs ossature bois"},
    {id:"mob_m2",label:"Surface MOB habitation (tout compris)",unit:"m²",hint:"Ossature + ITE PSE 100mm + laine 120mm + FV — 110,06 €/m² (tarif 2026)"},
    {id:"mob_etage_m2",label:"Surface MOB étage",unit:"m²",hint:"Même composition, tarif 102,41 €/m² — laisser 0 si plain-pied"},
    {id:"mob_pignon_m2",label:"Surface murs pignon (sans isolation)",unit:"m²",hint:"Ossature + OSB + ITE seule, sans laine — 128,39 €/m²"},
    {id:"mob_rehausse_m2",label:"Rehausse ossature bois (pignon R+1)",unit:"m²",hint:"Pignon intermédiaire non isolé — moy. 109 €/m²"},
    {id:"mob_garage_m2",label:"Surface murs garage (non isolés)",unit:"m²",hint:"Ossature + OSB + ITE — ~93,83 €/m²"},
    {id:"mob_95mm_m2",label:"MOB 45×95 sans ITE (cloison/refend)",unit:"m²",hint:"45,51 €/m² — 1 seul devis (faible fiabilité)"},
    {section:"🏠 Charpente"},
    {id:"charpente_ensemble_est",ensemble:true,label:"Fermette SICOB (estimation par m² de toiture)"},
    {id:"poutres_vent",label:"Poutres au vent (€)",unit:"€",hint:"Lire sur devis — moy. 650 €"},
    {id:"charpente_trad",label:"Charpente traditionnelle annexe (€)",unit:"€",hint:"Terrasse / toit plat / carport — lire sur devis"},
    {section:"🪵 Plancher R+1 (optionnel)"},
    {id:"solivage",label:"Solivage lamellé-collé R+1",unit:"forfait",hint:"1 = inclure (moy. 9 743 €), 0 = plain-pied"},
    {section:"🖼️ Habillage façade"},
    {id:"bandeau",label:"Bandeau façade PVC (€)",unit:"€",hint:"Blanc ou anthracite — moy. 380 €"},
    {id:"lambris",label:"Lambris débord / auvent PVC (€)",unit:"€",hint:"Blanc ou anthracite — moy. 390 €"},
    {id:"liteaux",label:"Liteaux + pare-pluie (€)",unit:"€",hint:"Support bardage — moy. 570 € (absent si bardage non prévu)"},
    {section:"🚚 Logistique"},
    {id:"transport",label:"Transport (€)",unit:"€",hint:"Z1 1009€ / Z2 1251€ / Z3 2270€ / Z4 3316€ — lire sur devis",default:1009}
  ],
  imaj: [
    {section:"📐 Murs ossature bois"},
    {id:"mob_m2",label:"Surface MOB tout compris",unit:"m²",hint:"Ossature + ITE 100mm + laine GR35 + pare-vapeur — prix fixe 95,37 €/m²"},
    {id:"mob_pignon_m2",label:"Surface murs pignon",unit:"m²",hint:"Non isolé + ITE 100mm — 83,26 €/m²"},
    {id:"mob_refend_m2",label:"Surface murs de refend",unit:"m²",hint:"Ossature 45×95 intérieure — 33,96 €/m²"},
    {section:"🏠 Charpente & toiture"},
    {id:"fermettes",label:"Fermettes industrielles",unit:"forfait",hint:"1 = inclure, 0 = sans"},
    {id:"charpente_trad",label:"Charpente traditionnelle (€)",unit:"€",hint:"Pannes, chevrons, arrêtier — lire sur devis"},
    {id:"toit_terrasse_m2",label:"Toit terrasse (m²)",unit:"m²",hint:"Solives 45×220 + OSB 18mm — 51,79 €/m²"},
    {section:"🪵 Plancher & structure (optionnel)"},
    {id:"plancher_clt",label:"Plancher CLT 120mm",unit:"forfait",hint:"1 = inclure, 0 = sans"},
    {id:"structure_bois",label:"Structure bois annexe (€)",unit:"€",hint:"Poteaux + sommiers — lire sur devis"},
    {section:"🔩 Frais annexes"},
    {id:"quincaillerie",label:"Quincaillerie chantier",unit:"forfait",hint:"1 = inclure (moy. 896 €)",default:1},
    {id:"etude",label:"Bureau d'études EXE/PAC (€)",unit:"€",hint:"Si prévu — moy. 1 589 €"},
    {section:"🚚 Logistique"},
    {id:"transport",label:"Transport semi-remorque (€)",unit:"€",hint:"550 à 2050€/semi selon distance — lire sur devis"}
  ],
  savare: [
    {section:"📐 Murs ossature bois"},
    {id:"mob_m2",label:"Surface MOB (ossature + ITE + laine tout compris)",unit:"m²",hint:"Taux composite moy. 110,30 €/m²"},
    {section:"🏠 Charpente"},
    {id:"fermettes",label:"Charpente industrielle",unit:"forfait",hint:"1 = inclure, 0 = sans"},
    {id:"charpente_trad",label:"Charpente traditionnelle (€)",unit:"€",hint:"Déplafonné, volumes spéciaux — lire sur devis"},
    {section:"🪵 Plancher & structure"},
    {id:"plancher_clt_m2",label:"Plancher CLT 120mm (m²)",unit:"m²",hint:"Hexapli 3L — moy. 147 €/m²"},
    {id:"structure_bois",label:"Structure poteau-poutre (€)",unit:"€",hint:"Poteaux 140×140 + poutres GL24H — lire sur devis"},
    {section:"📋 Frais fixes"},
    {id:"etude",label:"Études techniques",unit:"forfait",hint:"1 = inclure (moy. 1 745 €)",default:1},
    {section:"🚚 Logistique"},
    {id:"transport",label:"Transport MOB (€)",unit:"€",hint:"Normandie — moy. 2 606 €, lire sur devis"}
  ],
  lowall: [
    {section:"📐 Murs ossature bois"},
    {id:"mob_m2",label:"Surface MOB isolé (ITE PSE 100mm)",unit:"m²",hint:"Ossature 45x120 + laine 120mm + pare-vapeur + ITE PSE — 110 à 113 €/m²"},
    {id:"mob_ouvert_m2",label:"Surface MOB non isolé (ITE PSE seule)",unit:"m²",hint:"Garage, local technique — 85 €/m² fixe"},
    {id:"mob_biosource_m2",label:"Surface MOB bio-sourcé (ITE fibre de bois)",unit:"m²",hint:"Laine de bois + ITE fibre de bois — 132 €/m² — sur demande"},
    {section:"🔩 Quincaillerie"},
    {id:"quinc_qty",label:"Kit quincaillerie",unit:"m²",hint:"= MOB auto (10 €/m²)"},
    {section:"🏗️ Plancher & structure"},
    {id:"plancher_45x200_m2",label:"Plancher 45×200 (fourniture seule)",unit:"m²",hint:"Caisson ouvert chevrons 45×200 — 80 €/m² — portées courtes/moyennes"},
    {id:"plancher_80x220_m2",label:"Plancher 80×220 (fourniture seule)",unit:"m²",hint:"Caisson ouvert chevrons 80×220 — 90 €/m² — portées longues"},
    {id:"poteaux_poutres_m3",label:"Système poteaux-poutres",unit:"m³",hint:"Poteaux 160×160 + poutres 140×360 ou 160×400 — 1 000 €/m³ — lire volume sur devis"},
    {section:"🏠 Charpente"},
    {id:"fermettes",label:"Charpente (non fabriquée)",unit:"forfait",hint:"LOWALL ne fabrique pas de charpente"},
    {section:"🚚 Transport"},
    {id:"transport",label:"Transport plateau 13m (€)",unit:"€",hint:"Depuis Gardanne (13) — 1 100€ constaté (~45km). Lire sur devis, laisser 0 si non facturé"}
  ]
};

export const FIELD_TO_POSTE = {
  boisboreal:{
    mob_m2:{poste:"mob",type:"surface"},ite_m2:{poste:"ite100",type:"surface"},
    laine_m2:{poste:"laine120",type:"surface"},pv_m2:{poste:"pv",type:"surface"},
    protection_tete_ml:{poste:"protection_tete",type:"surface"},
    plancher_clt:{poste:"plancher_clt",type:"surface"},
    fermette_qty:{poste:"fermette",type:"forfait_qty"},
    vr_qty:{poste:"coffre_vr",type:"unite"},
    appuis_seuil_qty:{poste:"appuis_seuil",type:"unite"},
    chargement_m2:{poste:"chargement",type:"surface"},
    transport:{poste:"transport",type:"direct"},
    etude:{poste:"etude",type:"direct"}
  },
  cobs:{
    mob_m2:{poste:"mob",type:"surface"},isolation_m2:{poste:"isolation",type:"surface"},
    ite_m2:{poste:"ite100",type:"surface"},appui_qty:{poste:"appui",type:"unite"},
    pose_menui_qty:{poste:"pose_menui",type:"unite"},
    pose_coffre_qty:{poste:"pose_coffre",type:"unite"},
    charpente_m2:{poste:"charpente_indus",type:"surface"},
    plancher_m2:{poste:"plancher_solivage",type:"surface"},
    livraison:{poste:"livraison",type:"direct"},etude:{poste:"etude",type:"direct"}
  },
  sicob:{
    mob_m2:{poste:"mob_complet",type:"surface"},
    mob_etage_m2:{poste:"mob_etage",type:"surface"},
    mob_pignon_m2:{poste:"mob_pignon",type:"surface"},
    mob_rehausse_m2:{poste:"mob_rehausse",type:"surface"},
    mob_garage_m2:{poste:"mob_garage",type:"surface"},
    mob_95mm_m2:{poste:"mob_95mm",type:"surface"},
    fermettes:{poste:"fermettes",type:"forfait_qty"},
    poutres_vent:{poste:"poutres_vent",type:"direct"},
    charpente_trad:{poste:"charpente_trad",type:"direct"},
    solivage:{poste:"solivage",type:"forfait_qty"},
    bandeau:{poste:"bandeau",type:"direct"},
    lambris:{poste:"lambris",type:"direct"},
    liteaux:{poste:"liteaux",type:"direct"},
    transport:{poste:"transport",type:"direct"}
  },
  imaj:{
    mob_m2:{poste:"mob_complet",type:"surface"},
    mob_pignon_m2:{poste:"mob_pignon",type:"surface"},
    mob_refend_m2:{poste:"mob_refend",type:"surface"},
    fermettes:{poste:"fermettes",type:"forfait_qty"},
    charpente_trad:{poste:"charpente_trad",type:"direct"},
    toit_terrasse_m2:{poste:"toit_terrasse",type:"surface"},
    plancher_clt:{poste:"plancher_clt",type:"forfait_qty"},
    structure_bois:{poste:"structure_bois",type:"direct"},
    quincaillerie:{poste:"quincaillerie",type:"forfait_qty"},
    etude:{poste:"etude",type:"direct"},
    transport:{poste:"transport",type:"direct"}
  },
  savare:{
    mob_m2:{poste:"mob_composite",type:"surface"},
    fermettes:{poste:"fermettes",type:"forfait_qty"},
    charpente_trad:{poste:"charpente_trad",type:"direct"},
    plancher_clt_m2:{poste:"plancher_clt",type:"surface"},
    structure_bois:{poste:"structure_bois",type:"direct"},
    etude:{poste:"etude",type:"forfait_qty"},
    transport:{poste:"transport",type:"direct"}
  },
  lowall:{
    mob_m2:{poste:"mob",type:"surface"},
    mob_ouvert_m2:{poste:"mob_ouvert",type:"surface"},
    mob_biosource_m2:{poste:"mob_biosource",type:"surface"},
    quinc_qty:{poste:"quincaillerie",type:"surface"},
    plancher_45x200_m2:{poste:"plancher_45x200",type:"surface"},
    plancher_80x220_m2:{poste:"plancher_80x220",type:"surface"},
    poteaux_poutres_m3:{poste:"poteaux_poutres",type:"volume"},
    fermettes:{poste:"fermettes",type:"forfait_qty"},
    transport:{poste:"transport",type:"direct"}
  }
};
