/* eslint-disable */
export const REFS = {
  boisboreal: {
    nom:"BoisBoréal",couleur:"#2B4A1A",devis_count:15,derniere_maj:"2026-04-29",
    description:"Fabricant Vendée — agences Ouest et Sud",
    postes:{
      etude:        {label_user:"Bureau d'étude",label_pdf:"Bureau d'étude",tooltip:"Carnet de détail, plan EXE, mise en fabrication, plan de pose. Forfait quasi figé.",unite:"forfait",moyen:1930.40,min:1824,max:1938,n:15,fiabilite:"haute",visible:true},
      mob:          {label_user:"Murs ossature bois",label_pdf:"Fourniture Murs Ossature Bois extérieur",tooltip:"Montant + lisse 45×120 épicéa CL2, lisse d'ancrage CL3, EPDM, voile OSB3 12mm, bracon, quincaillerie de pose.",unite:"€/m²",moyen:42.95,min:35.34,max:52.69,n:15,fiabilite:"haute",visible:true},
      ite100:       {label_user:"ITE PSE 100mm + tableaux de menuiserie",label_pdf:"Fourniture et pose ITE isolation PSE",tooltip:"PRB FACADE TH38 100mm, R=2,60. Pose en préfabrication atelier. Inclut tableaux de menuiserie.",unite:"€/m²",moyen:39.36,min:34.19,max:40.57,n:15,fiabilite:"haute",visible:true},
      laine120:     {label_user:"Laine de verre 120mm (isolation MOB)",label_pdf:"Fourniture et Pose de laine de verre",tooltip:"KI FIT 032, R=3,75. Intégrée dans l'ossature bois en atelier.",unite:"€/m²",moyen:14.97,min:12.12,max:16.51,n:15,fiabilite:"haute",visible:true},
      pv:           {label_user:"Pare-vapeur SD100",label_pdf:"Fourniture et pose Pare Vapeur SD100",tooltip:"Pare-vapeur SD100 intégré au MOB.",unite:"€/m²",moyen:8.41,min:7.58,max:9.18,n:15,fiabilite:"haute",visible:true},
      protection_tete:{label_user:"Protection en tête de MOB",label_pdf:"Protection tête de MOB",tooltip:"Protection horizontale en tête de murs. Auto-calculé = MOB −30% (en ML). Prix catalogue : 4,60 €/ML.",unite:"€/ML",moyen:4.60,min:4.60,max:4.60,n:15,fiabilite:"haute",visible:true},
      appuis_seuil: {label_user:"Appuis et seuil PSE",label_pdf:"Appuis et seuils PSE",tooltip:"Appuis de fenêtre et seuils en PSE préfabriqués. Prix unitaire : 59,29 €/u.",unite:"€/u",moyen:59.29,min:59.29,max:59.29,n:15,fiabilite:"haute",visible:true},
      transport:    {label_user:"Transport (auto)",label_pdf:"Prestation de transport MOB",tooltip:"1 forfait si MOB < 141m² sans plancher. 2 forfaits si MOB ≥ 141m², ou MOB < 141m² avec plancher. Prix forfait : 1 268 €.",unite:"€",moyen:1268,min:0,max:3140,n:15,fiabilite:"haute",visible:true},
      chargement:   {label_user:"Chargement atelier (5,17 €/m²)",label_pdf:"Chargement MOB",tooltip:"Coût de chargement atelier. Forfait fixe de 5,17 €/m² de MOB. Auto-calculé depuis le m² de murs ossature bois.",unite:"€/m²",moyen:5.17,min:5.17,max:5.17,n:15,fiabilite:"haute",visible:true},
      plancher_clt: {label_user:"Plancher CLT 140 5L",label_pdf:"Fourniture planchers CLT",tooltip:"Plancher 5 plis lamellé-croisé 140mm. Traitements PARKA + CT2 incolore.",unite:"€/m²",moyen:197.83,min:178.02,max:220.86,n:4,fiabilite:"faible",visible:true},
      fermette:     {label_user:"Charpente fermette (ensemble)",label_pdf:"Fourniture de Fermettes",tooltip:"Fermettes industrielles. Inclut équerres, vis bois, sablière, contreventement, AFA.",unite:"forfait",moyen:3500,min:2237,max:4536,n:8,fiabilite:"moyenne",visible:true},
      coffre_vr:    {label_user:"Coffre volet roulant",label_pdf:"Intégration des Coffres Volet-Roulants dans MOB",tooltip:"Coffrelite. Fourniture par tes soins, pose en atelier intégrée au MOB.",unite:"€/u",moyen:42.10,min:32.30,max:48.45,n:12,fiabilite:"haute",visible:true}
    }
  },
  cobs: {
    nom:"COBS / GIPEN",couleur:"#5A7A3A",devis_count:6,derniere_maj:"2026-03-06",
    description:"Fabricant Savoie — agences Est et Sud-Est",
    postes:{
      etude:            {label_user:"Étude complète",label_pdf:"Etude complète",tooltip:"Étude complète d'exécution.",unite:"forfait",moyen:1000,min:750,max:1500,n:6,fiabilite:"moyenne",visible:true},
      mob:              {label_user:"Paroi ossature bois",label_pdf:"Paroi ossature bois maison",tooltip:"Lisses CLIV 45×95 et 45×120, ossature épicéa 45×120 + voile contreventement 15mm.",unite:"€/m²",moyen:54.00,min:48.86,max:61.18,n:6,fiabilite:"moyenne",visible:true},
      isolation:        {label_user:"Isolation MOB (laine 120mm + pare-vapeur)",label_pdf:"Isolation de la structure",tooltip:"Laine de verre GR 32 120mm (pose atelier) + gestion étanchéité à l'air en pied + pare-vapeur intégré.",unite:"€/m²",moyen:19.99,min:18.69,max:21.18,n:6,fiabilite:"moyenne",visible:true},
      ite100:           {label_user:"ITE polystyrène 100mm",label_pdf:"Finition extérieure pour pose d'enduit sur ITE",tooltip:"Polystyrène 100mm posé en atelier. Pour réception d'enduit. Très stable sur 6 devis : 27,00 à 27,81€/m².",unite:"€/m²",moyen:27.60,min:26.78,max:28.62,n:6,fiabilite:"moyenne",visible:true},
      appui:            {label_user:"Pièce d'appui béton préfa",label_pdf:"Pièce d'appui passage",tooltip:"Pièce d'appui béton préfabriqué pour passages de menuiseries. Valeur moyenne par ouverture (mix passage + fenêtre). Dispersion élevée selon projet.",unite:"€/u",moyen:92.76,min:41.20,max:166.40,n:6,fiabilite:"moyenne",visible:true},
      pose_menui:       {label_user:"Pose menuiserie en atelier",label_pdf:"POSE DE MENUISERIE",tooltip:"Pose en atelier, compris gestion de l'étanchéité à l'air. Volet roulant ou BSO si présents.",unite:"€/u",moyen:70,min:70,max:70,n:2,fiabilite:"faible",visible:true},
      pose_coffre:      {label_user:"Pose de coffre",label_pdf:"POSE DE COFFRE",tooltip:"Pose de coffre volet roulant en atelier. 10 €/u.",unite:"€/u",moyen:10,min:10,max:10,n:1,fiabilite:"faible",visible:true},
      charpente_indus:  {label_user:"Charpente industrielle (fermettes)",label_pdf:"Charpente industrielle",tooltip:"Fermettes, pannes, chevrons en débord de toiture, contreventement. Dispersion élevée (23 à 49€/m²) selon complexité.",unite:"€/m²",moyen:33.36,min:23.74,max:48.81,n:6,fiabilite:"moyenne",visible:true},
      plancher_solivage:{label_user:"Plancher solivage BLC",label_pdf:"Solivage plancher",tooltip:"Solivage porteur épicéa BMA + CC C24, LC GL24 traité CL2. Charge 150 kg/m² + exploitation 150 kg/m².",unite:"€/m²",moyen:96.89,min:67.07,max:112.99,n:4,fiabilite:"faible",visible:true},
      livraison:        {label_user:"Livraison (forfait)",label_pdf:"Livraison",tooltip:"Transport sans levage. 110 €/h si levage demandé. Accès stabilisé requis.",unite:"forfait",moyen:2205,min:1360,max:3560,n:6,fiabilite:"moyenne",visible:true}
    }
  },
  sicob: {
    nom:"SICOB",couleur:"#8B4513",devis_count:32,derniere_maj:"2026-04-17",
    description:"Charpentier-couvreur Aveyron (12240 Rieupeyroux) — agences Midi-Pyrénées, Occitanie, PACA",
    postes:{
      mob_complet:    {label_user:"MOB 45×120 tout compris (ossature + ITE PSE 100 + laine 120 + FV)",label_pdf:"MURS OSSATURE BOIS",tooltip:"TARIF 2026 : 110,06 €/m² (vs 103,91 €/m² en 2025, +5,9%). Inclut : lisse 42×120 CL3, ossature 45×120 C24 CL2, OSB 12mm, ITE PSE 100mm (R=2.60), laine verre 120mm (R=3.40), frein vapeur, scotch, appuis allège, coffres VR.",unite:"€/m²",moyen:110.06,min:103.91,max:110.06,n:32,fiabilite:"haute",visible:true},
      mob_etage:      {label_user:"MOB étage (tarif légèrement réduit)",label_pdf:"MURS OSSATURE BOIS ETAGE",tooltip:"Même composition que MOB standard. Présent sur 4 devis 2025 à 102,41 €/m². Données 2026 sur R+1 utilisent le tarif habitation standard.",unite:"€/m²",moyen:102.41,min:102.41,max:102.41,n:4,fiabilite:"faible",visible:true},
      mob_pignon:     {label_user:"Mur pignon (sans laine ni FV — ITE seule)",label_pdf:"MURS OSSATURE BOIS PIGNON",tooltip:"TARIF 2026 : 128,39 à 130,65 €/m² (vs 94,80 €/m² en 2025, +35%). Ossature 45×120 + OSB + ITE PSE 100mm, SANS laine de verre ni frein vapeur. Pour murs pignons sous combles perdus.",unite:"€/m²",moyen:128.39,min:94.80,max:130.65,n:16,fiabilite:"haute",visible:true},
      mob_rehausse:   {label_user:"Rehausse ossature bois (pignon intermédiaire R+1)",label_pdf:"REHAUSSE OSSATURE BOIS",tooltip:"Mur pignon non isolé type 2026. Varie selon devis : 105,52 à 122,96 €/m². Sans laine de verre ni frein vapeur, avec ITE PSE 100mm. Présent sur les projets R+1 et projets publics.",unite:"€/m²",moyen:109.00,min:105.52,max:122.96,n:6,fiabilite:"moyenne",visible:true},
      mob_garage:     {label_user:"Mur garage (non isolé — ITE seule)",label_pdf:"MUR OSSATURE BOIS GARAGE",tooltip:"Ossature 45×120 + OSB + ITE, SANS isolation thermique. Tarif 2025-2026 : 91,28 à 95,20 €/m².",unite:"€/m²",moyen:93.83,min:91.28,max:95.20,n:4,fiabilite:"faible",visible:true},
      mob_95mm:       {label_user:"MOB 45×95 sans ITE (cloison/refend int.)",label_pdf:"FOURNITURE MURS OSSATURE BOIS 95 MM COMPRIS ISOLATION",tooltip:"Ossature 45×95 + OSB 12mm, sans ITE. Pour cloisons intérieures ou refends. Tarif : 45,51 €/m² (1 seul devis — faible fiabilité).",unite:"€/m²",moyen:45.51,min:45.51,max:45.51,n:1,fiabilite:"faible",visible:true},
      fermettes:      {label_user:"Charpente fermette (forfait ensemble)",label_pdf:"FERMETTES",tooltip:"Fermettes épicéa C24 CL2, entraxe 60 cm. Très variable : 2 pentes tuile ≈ 1 600-2 900€ / 6 pentes ardoise/croupes ≈ 4 300-10 000€. 32 devis disponibles.",unite:"forfait",moyen:3350,min:1003,max:9956,n:32,fiabilite:"haute",visible:true},
      solivage:       {label_user:"Solivage lamellé-collé (plancher R+1)",label_pdf:"SOLIVAGE",tooltip:"Plancher inter-niveaux en épicéa lamellé-collé : porteurs, porteur périphérique, poteaux, ceinture, plancher CLT 100mm ou CTBH. 4 devis R+1 disponibles.",unite:"forfait",moyen:9743,min:9530,max:9910,n:4,fiabilite:"faible",visible:true},
      poutres_vent:   {label_user:"Poutres au vent",label_pdf:"POUTRES AU VENT",tooltip:"Poutres au vent ML + appliques 36×97 TC2 + boulons 12×140. Montant variable selon portée. Présent sur 50% des devis.",unite:"€",moyen:650,min:211,max:2195,n:16,fiabilite:"haute",visible:true},
      charpente_trad: {label_user:"Charpente traditionnelle annexe (terrasse / toit plat)",label_pdf:"FOURNITURE TRADITIONNEL EPICEA",tooltip:"Pannes, poteaux, chevrons, solives épicéa traité. Terrasses, carports, toits-terrasses.",unite:"€",moyen:950,min:372,max:1628,n:10,fiabilite:"haute",visible:true},
      bandeau:        {label_user:"Bandeau façade (PVC blanc ou anthracite)",label_pdf:"BANDEAU 20 PVC BLANC",tooltip:"RIVECEL L9 h.175-200mm en PVC blanc ou anthracite. Prix variable selon longueur de façade.",unite:"€",moyen:380,min:144,max:617,n:22,fiabilite:"haute",visible:true},
      lambris:        {label_user:"Lambris auvent / débord de toit (PVC ou bois)",label_pdf:"LAMBRIS PVC BLANC",tooltip:"Lambris alvéolaire PVC 0.25m×4ml blanc ou anthracite, ou lambris épicéa CL3M.",unite:"€",moyen:390,min:100,max:767,n:22,fiabilite:"haute",visible:true},
      liteaux:        {label_user:"Liteaux + pare-pluie (support bardage)",label_pdf:"LITEAUX / PARE PLUIE",tooltip:"Liteaux 18×47 et 27×38 TC2 + rouleau pare-pluie HPV R2. Présent sur ~60% des devis. Absent quand bardage non prévu.",unite:"€",moyen:570,min:341,max:1025,n:14,fiabilite:"haute",visible:true},
      transport:      {label_user:"Transport (selon zone)",label_pdf:"TRANSPORT",tooltip:"Z1 (12,15,46,81 proche) : 1 009 € (2×504,50€). Z2 (11,19,24,31,32,47,48,82) : 1 251 €. Z3 (30,34 éloigné) : ~2 270 € (2×1 135€). Z4 (zone très éloignée) : ~3 316 € (3×1 105€). Non compris déchargement.",unite:"€",moyen:1200,min:326,max:3316,n:32,fiabilite:"haute",visible:true}
    }
  },
  imaj: {
    nom:"IMAJ",couleur:"#1A5276",devis_count:5,derniere_maj:"2026-03-04",
    description:"Fabricant MOB Lot-et-Garonne (47200 Marmande) — agences Sud-Ouest",
    postes:{
      mob_complet:    {label_user:"MOB tout compris (ossature + ITE + laine + FV)",label_pdf:"Mur ossature 45x120, OSB 12mm, laine de verre GR35, pare-vapeur Sd>90, ITE PSE 100mm",tooltip:"Prix FIXE 95,37 €/m² sur tous les devis. Inclut : ossature 45×120, OSB 12mm, laine GR35, pare-vapeur Sd>90, ITE PSE 100mm.",unite:"€/m²",moyen:95.37,min:95.37,max:95.37,n:5,fiabilite:"moyenne",visible:true},
      mob_pignon:     {label_user:"Mur pignon (non isolé + ITE PSE 100mm)",label_pdf:"Mur pignon ossature 45x120, OSB 12mm, non isolé, ITE PSE 100mm",tooltip:"Ossature 45×120 + OSB 12mm + ITE PSE 100mm, sans laine de verre ni pare-vapeur. 1 seul point de données.",unite:"€/m²",moyen:83.26,min:83.26,max:83.26,n:1,fiabilite:"faible",visible:true},
      mob_refend:     {label_user:"Mur de refend intérieur (ossature 45×95, OSB)",label_pdf:"Mur de refend 45x95, OSB 12mm",tooltip:"Cloison porteuse intérieure. Ossature 45×95 + voile OSB 12mm. Sans isolation ni ITE. 1 seul point.",unite:"€/m²",moyen:33.96,min:33.96,max:33.96,n:1,fiabilite:"faible",visible:true},
      fermettes:      {label_user:"Fermettes industrielles (forfait)",label_pdf:"Fermettes industrielles",tooltip:"Charpente industrielle complète. Prix très variable selon la forme de toiture.",unite:"forfait",moyen:5592,min:2605,max:9766,n:5,fiabilite:"moyenne",visible:true},
      plancher_clt:   {label_user:"Plancher CLT 120mm (forfait)",label_pdf:"Plancher CLT 120mm",tooltip:"Plancher lamellé-croisé 120mm pour maisons à étage. Seulement 2 devis disponibles.",unite:"forfait",moyen:11900,min:9239,max:14561,n:2,fiabilite:"faible",visible:true},
      toit_terrasse:  {label_user:"Toit terrasse (solives 45×220, OSB 18mm)",label_pdf:"Toit terrasse - solives 45x220, OSB 18mm dalle, ligneuls",tooltip:"Structure toit terrasse : solives 45×220, dalle OSB 18mm, ligneuls. 1 seul devis disponible (SONZOGNY).",unite:"€/m²",moyen:51.79,min:51.79,max:51.79,n:1,fiabilite:"faible",visible:true},
      structure_bois: {label_user:"Structure bois annexe (poteaux + sommiers)",label_pdf:"Structure plancher - poteaux 180x180",tooltip:"Structure bois inter-niveaux ou extérieure : poteaux 180×180 + sommiers LC ou cl.2.",unite:"€",moyen:1589,min:926,max:2252,n:2,fiabilite:"faible",visible:true},
      charpente_trad: {label_user:"Charpente traditionnelle (pannes, chevrons, arrêtier)",label_pdf:"Charpente tradi",tooltip:"Charpente bois traditionnelle : pannes, chevrons, abouts de chevrons, arrêtier.",unite:"€",moyen:4056,min:4056,max:4056,n:1,fiabilite:"faible",visible:true},
      quincaillerie:  {label_user:"Quincaillerie chantier (forfait)",label_pdf:"Quincaillerie chantier",tooltip:"Joint 15×15, équerres AKRX3, E5, ABR100, vis béton 12×120, adhésif Riwega Tape Green, bande d'arase. Toujours facturée séparément chez IMAJ.",unite:"forfait",moyen:896,min:685,max:1219,n:5,fiabilite:"moyenne",visible:true},
      etude:          {label_user:"Bureau d'études (plans EXE et PAC)",label_pdf:"Prestation Bureau d'études",tooltip:"Plans d'exécution et PAC. Pas systématique — vérifier sur le devis.",unite:"forfait",moyen:1589,min:1549,max:1629,n:2,fiabilite:"faible",visible:true},
      transport:      {label_user:"Transport semi-remorque (sans grue)",label_pdf:"Transport - semi-remorque",tooltip:"Semi-remorque sans grue. 550€/semi (courte distance) à 2050€/semi (longue distance). Nombre de semis variable selon projet.",unite:"€",moyen:2120,min:550,max:4100,n:5,fiabilite:"moyenne",visible:true}
    }
  },
  savare: {
    nom:"SAVARE (Eiffage)",couleur:"#C0392B",devis_count:5,derniere_maj:"2025-04-08",
    description:"Fabricant MOB Normandie (Lessay 50 / Moult 14) — agences Normandie, Grand Ouest, Nord",
    postes:{
      mob_composite:  {label_user:"Ossature bois tout compris (MOB + ITE + laine + pare-vapeur)",label_pdf:"Total OSSATURE BOIS",tooltip:"Taux composite = Total section Ossature Bois / m² MOB principal. Inclut : ossature 45×120, OSB 12mm, laine 120mm + pare-vapeur, ITE PSE 100mm, profil socle, isolation ouvertures, pare-pluie si bardage.",unite:"€/m²",moyen:110.30,min:97.61,max:120.09,n:5,fiabilite:"moyenne",visible:true},
      fermettes:      {label_user:"Charpente industrielle (ensemble section)",label_pdf:"Total CHARPENTE INDUSTRIELLE",tooltip:"Total de la section Charpente Industrielle : fermettes connectées/agrafées, accessoires, contreventement, quincaillerie, chevalets de renfort, débords PVC.",unite:"forfait",moyen:4203,min:2167,max:8439,n:5,fiabilite:"moyenne",visible:true},
      plancher_clt:   {label_user:"Plancher CLT 120mm (solivage porteur)",label_pdf:"SOLIVAGE PORTEUR CLT",tooltip:"Panneaux CLT Hexapli 120mm 3L + OSB dalle 22mm. Pour R+1. 3 devis disponibles.",unite:"€/m²",moyen:147.10,min:141.71,max:157.44,n:3,fiabilite:"faible",visible:true},
      charpente_trad: {label_user:"Charpente traditionnelle (pannes, chevrons, muralières)",label_pdf:"CHARPENTE TRADITIONNELLE",tooltip:"Pannes, chevrons, muralières, sablières épicéa C24. Pour espaces déplafonnés ou volumes spéciaux.",unite:"€",moyen:915,min:414,max:1415,n:2,fiabilite:"faible",visible:true},
      structure_bois: {label_user:"Structure poteau-poutre (poteaux 140×140 + poutres GL24H)",label_pdf:"ENSEMBLE POTEAU - POUTRE",tooltip:"Poteaux épicéa C24 140×140 + poutres GL24H 140×360 + sabots GLE + équerres.",unite:"€",moyen:1048,min:467,max:1628,n:2,fiabilite:"faible",visible:true},
      etude:          {label_user:"Études techniques (systématique SAVARE)",label_pdf:"ETUDES TECHNIQUES",tooltip:"Études de conception et d'exécution. Toujours présentes chez SAVARE. Moy. 1745€.",unite:"forfait",moyen:1745,min:1418,max:2100,n:5,fiabilite:"moyenne",visible:true},
      transport:      {label_user:"Transport MOB (depuis Normandie)",label_pdf:"TRANSPORT MOB",tooltip:"Transport depuis usine SAVARE (Normandie). Prix variable selon distance et nombre de camions.",unite:"€",moyen:2606,min:2100,max:3861,n:5,fiabilite:"moyenne",visible:true}
    }
  },
  lowall: {
    nom:"LOWALL",couleur:"#2E7D7D",devis_count:15,derniere_maj:"2026-05-11",
    description:"Fabricant panneaux MOB Bouches-du-Rhône (Gardanne 13) — agences PACA. Pas de charpente.",
    postes:{
      mob:          {label_user:"MOB isolé 45x120 (ITE PSE 100mm)",label_pdf:"Murs Ossature Bois Isolé 45x120",tooltip:"Ossature 45x120, OSB3 13mm, laine de roche/verre 120mm, pare-vapeur, ITE PSE 100+40mm. Tarif standard : 110€/m² (Avignon/84) · 113€/m² (Salon/Toulon). Moy. 14 devis : 110,64€/m².",unite:"€/m²",moyen:110.64,min:110,max:113,n:14,fiabilite:"haute",visible:true},
      mob_biosource:{label_user:"MOB isolé bio-sourcé (laine de bois + ITE fibre)",label_pdf:"Murs Ossature Bois Isolé 45x120 bio-sourcé",tooltip:"Ossature 45x120, OSB3, laine de bois 120mm, pare-vapeur, ITE fibre de bois 100+40mm (assemblage knapp). Tarif : 132€/m² — 1 seul devis TORDOIR (Avignon). Sur demande spécifique.",unite:"€/m²",moyen:132,min:132,max:132,n:1,fiabilite:"faible",visible:true},
      mob_ouvert:   {label_user:"MOB non isolé 45x120 (ITE PSE seule)",label_pdf:"Murs Ossature Bois Ouvert 45x120",tooltip:"Ossature 45x120, OSB3 13mm, ITE PSE 100+40mm uniquement. Sans laine ni pare-vapeur. Pour garages, locaux techniques ou pignons non chauffés. Tarif fixe : 85€/m² sur 6 devis.",unite:"€/m²",moyen:85,min:85,max:85,n:6,fiabilite:"moyenne",visible:true},
      quincaillerie:{label_user:"Kit quincaillerie",label_pdf:"Kit Quincaillerie",tooltip:"Bandes d'arase 2 joints mousses, équerres E8/2.5 ou AH (sismique), E5/1.5, fixation (tiges+tamis+résine), colle PU+vis mibois, profilé mâle/femelle. 10€/m² d'ossature — fixe sur 15 devis.",unite:"€/m²",moyen:10,min:10,max:10,n:15,fiabilite:"haute",visible:true},
      plancher_45x200:{label_user:"Modules plancher 45×200 (fourniture seule)",label_pdf:"Modules Plancher 45x200",tooltip:"Caisson ouvert : Dalle OSB3 22mm face sup + Chevrons 45×200 + OSB3 9mm sous-face. Fourniture seulement, pose à la charge du chantier. Tarif : 80€/m² — 1 devis JUNK (Toulon). Pour portées courtes/moyennes.",unite:"€/m²",moyen:80,min:80,max:80,n:1,fiabilite:"faible",visible:true},
      plancher_80x220:{label_user:"Modules plancher 80×220 (fourniture seule)",label_pdf:"Modules Plancher 80x220",tooltip:"Caisson ouvert : Dalle OSB3 22mm face sup + Chevrons 80×220 + OSB3 9mm sous-face. Fourniture seulement, pose à la charge du chantier. Tarif : 90€/m² — 1 devis BRETTON (Toulon). Pour portées longues.",unite:"€/m²",moyen:90,min:90,max:90,n:1,fiabilite:"faible",visible:true},
      poteaux_poutres:{label_user:"Système poteaux-poutres",label_pdf:"Système Poteaux Poutres",tooltip:"Poteaux 160×160 + poutres 140×360 ou 160×400 (à vérifier en phase EXE). Chiffré au m³ de bois. Tarif fixe : 1 000 €/m³ — 2 devis (BRETTON + JUNK à Toulon).",unite:"€/m³",moyen:1000,min:1000,max:1000,n:2,fiabilite:"moyenne",visible:true},
      fermettes:    {label_user:"Charpente fermette",label_pdf:"",tooltip:"LOWALL ne fabrique pas de charpente. Prévoir charpentier externe.",unite:"forfait",moyen:0,min:0,max:0,n:0,fiabilite:"faible",visible:false},
      transport:    {label_user:"Transport plateau 13m",label_pdf:"Transport par camion plateau",tooltip:"Transport depuis Gardanne (13). 1 100€/forfait constaté. Plusieurs camions possibles (col de cygne pour murs >3m). Lire sur devis : nb de forfaits × 1 100€.",unite:"€",moyen:1100,min:1100,max:1100,n:4,fiabilite:"moyenne",visible:true}
    }
  }
};
