/* eslint-disable */
export const DQ = [
  {q:"Face à un obstacle, vous avez tendance à :",opts:[{t:"Foncer directement pour le résoudre",d:"D"},{t:"Convaincre les autres de vous aider",d:"I"},{t:"Chercher un consensus et être patient",d:"S"},{t:"Analyser soigneusement avant d'agir",d:"C"}]},
  {q:"En réunion d'équipe, vous êtes surtout perçu comme :",opts:[{t:"Celui qui prend les décisions rapidement",d:"D"},{t:"Celui qui motive et enthousiasme le groupe",d:"I"},{t:"Celui qui écoute et apaise les tensions",d:"S"},{t:"Celui qui vérifie les données et les faits",d:"C"}]},
  {q:"Lorsque vous gérez un projet, votre priorité est :",opts:[{t:"Atteindre les résultats dans les délais",d:"D"},{t:"Créer une bonne ambiance dans l'équipe",d:"I"},{t:"Assurer la stabilité et le suivi régulier",d:"S"},{t:"Garantir la qualité et la précision",d:"C"}]},
  {q:"Votre façon de prendre une décision importante :",opts:[{t:"Rapidement, sur la base de votre intuition",d:"D"},{t:"En consultant et en impliquant les autres",d:"I"},{t:"Prudemment, après réflexion collective",d:"S"},{t:"Après avoir rassemblé beaucoup d'informations",d:"C"}]},
  {q:"Comment réagissez-vous à la pression ?",opts:[{t:"Vous aimez ça, ça vous stimule",d:"D"},{t:"Vous cherchez du soutien autour de vous",d:"I"},{t:"Vous restez calme et gérez méthodiquement",d:"S"},{t:"Vous analysez pour réduire l'incertitude",d:"C"}]},
  {q:"Dans votre communication, vous êtes plutôt :",opts:[{t:"Direct et concis",d:"D"},{t:"Expressif et chaleureux",d:"I"},{t:"Attentif et à l'écoute",d:"S"},{t:"Précis et factuel",d:"C"}]},
  {q:"Vous vous épanouissez surtout dans un environnement :",opts:[{t:"Compétitif et ambitieux",d:"D"},{t:"Dynamique et créatif",d:"I"},{t:"Stable, collaboratif et prévisible",d:"S"},{t:"Structuré, avec des règles claires",d:"C"}]},
  {q:"Face à un désaccord, vous :",opts:[{t:"Défendez votre position avec vigueur",d:"D"},{t:"Cherchez à réconcilier les deux parties",d:"I"},{t:"Évitez le conflit et préférez la paix",d:"S"},{t:"Exposez les faits pour trouver la bonne solution",d:"C"}]},
  {q:"Votre point fort en tant que manager serait :",opts:[{t:"Votre capacité à orienter et décider",d:"D"},{t:"Votre charisme et sens du collectif",d:"I"},{t:"Votre patience et loyauté envers l'équipe",d:"S"},{t:"Votre rigueur et souci du détail",d:"C"}]},
  {q:"Ce qui vous motive le plus dans un projet :",opts:[{t:"Le défi à relever et la victoire",d:"D"},{t:"L'enthousiasme et la reconnaissance",d:"I"},{t:"La stabilité et la progression régulière",d:"S"},{t:"La maîtrise et la perfection du résultat",d:"C"}]},
  {q:"Votre style de leadership :",opts:[{t:"Autoritaire et orienté résultats",d:"D"},{t:"Inspirant et fédérateur",d:"I"},{t:"Bienveillant et participatif",d:"S"},{t:"Analytique et méthodique",d:"C"}]},
  {q:"Dans une négociation, vous :",opts:[{t:"Imposez vos conditions clairement",d:"D"},{t:"Utilisez votre charme pour convaincre",d:"I"},{t:"Cherchez un accord équitable pour tous",d:"S"},{t:"Préparez des arguments précis et documentés",d:"C"}]},
  {q:"Face à un changement inattendu, vous :",opts:[{t:"Saisissez l'opportunité sans hésiter",d:"D"},{t:"Enthousiasmez les autres face au changement",d:"I"},{t:"Prenez le temps de vous adapter progressivement",d:"S"},{t:"Évaluez les risques avant tout",d:"C"}]},
  {q:"Votre principale faiblesse en situation de stress :",opts:[{t:"Vous pouvez devenir trop directif",d:"D"},{t:"Vous pouvez manquer de rigueur ou de suivi",d:"I"},{t:"Vous pouvez résister au changement",d:"S"},{t:"Vous pouvez vous perdre dans les détails",d:"C"}]},
  {q:"Quand vous gérez un point de vente, vous privilégiez :",opts:[{t:"La performance et les objectifs",d:"D"},{t:"L'ambiance et la satisfaction client",d:"I"},{t:"La régularité et la fidélisation",d:"S"},{t:"Les process et la conformité aux standards",d:"C"}]},
  {q:"Votre rapport au risque professionnel :",opts:[{t:"Vous aimez prendre des risques calculés",d:"D"},{t:"Vous acceptez le risque si l'aventure est belle",d:"I"},{t:"Vous préférez la sécurité et la stabilité",d:"S"},{t:"Vous minimisez le risque par l'analyse",d:"C"}]},
  {q:"Comment gérez-vous vos équipes ?",opts:[{t:"Par la performance et les objectifs chiffrés",d:"D"},{t:"Par la motivation et la dynamique de groupe",d:"I"},{t:"Par la confiance et le soutien au quotidien",d:"S"},{t:"Par les procédures et le respect des règles",d:"C"}]},
  {q:"Votre rapport aux délais :",opts:[{t:"Vous êtes très exigeant sur les délais",d:"D"},{t:"Vous êtes flexible, l'important c'est le résultat",d:"I"},{t:"Vous planifiez soigneusement pour tenir les délais",d:"S"},{t:"Vous êtes précis sur les plannings et les étapes",d:"C"}]},
  {q:"La réussite d'une franchise, c'est avant tout :",opts:[{t:"Dépasser les objectifs commerciaux",d:"D"},{t:"Créer une belle expérience client et collaborateur",d:"I"},{t:"Bâtir une activité pérenne et stable",d:"S"},{t:"Appliquer les standards du réseau à la perfection",d:"C"}]},
  {q:"Dans 5 ans, vous vous voyez :",opts:[{t:"Leader dans le réseau, avec plusieurs unités",d:"D"},{t:"Ambassadeur de la marque, reconnu et influent",d:"I"},{t:"Franchisé solide, épanoui dans votre unité",d:"S"},{t:"Expert opérationnel, garant de la qualité réseau",d:"C"}]}
] as const;
export const DP = {D:{name:'Dominant',desc:"Orienté résultats, décideur, compétitif. Direct et ambitieux, vous prenez des risques calculés pour atteindre vos objectifs."},I:{name:'Influent',desc:"Enthousiaste, communicatif et fédérateur. Votre charisme et sens des relations font de vous un excellent animateur d'équipe."},S:{name:'Stable',desc:"Fiable, loyal et orienté équipe. Patience et constance, vous valorisez les relations durables et la stabilité."},C:{name:'Consciencieux',desc:"Analytique, précis, soucieux de la qualité. Votre rigueur et respect des process garantissent la conformité réseau."}} as const;
