/** Auto-generated by scripts/write-environment.mjs — do not edit or commit */
export const environment = {
  production: false,
  supabaseUrl: 'https://rrhaubqmcetgmjhqweyr.supabase.co',
  supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyaGF1YnFtY2V0Z21qaHF3ZXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0OTQwNDIsImV4cCI6MjA5NjA3MDA0Mn0.V0dbqyHxa3MOUk1-V7B7_b39SGXmnyQtIDtMY_zJX8U',
  sentryDsn: 'https://7be1d68a98d38f0c97e8e9252d39b302@o4511343914516480.ingest.de.sentry.io/4511517610016848',
};
